password_generator/generator/urls.py
from django.urls import path
from .views import generate_password, password, sorry

app_name = 'generator'

urlpatterns = [
    path('', generate_password, name='gen'),
    path('password/', password, name='pwd'),
    path('oh_my_god/', sorry, name='sorry')
]

password_generator/password_generator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('generator.urls', namespace='generator'))
]

password_generator/generator/views.py
import string, random
from django.shortcuts import render



# Create your views here.

def generate_password(request):

    context = {

    }
    return render(request, template_name='generator/gen.html', context={})

def password(request):
    pwd = ''
    length = int(request.GET.get('length'))
    chars = string.ascii_lowercase
    if request.GET.get('uppercase'):
        chars += string.ascii_uppercase
    if request.GET.get('numbers'):
        chars += string.digits
    if request.GET.get('special'):
        chars += string.punctuation
    for i in range(length):
        pwd += random.choice(chars)
    return render(request, template_name='generator/password.html', context={'length':length, 'pwd':pwd})


def sorry(request):
    return render(request, template_name='generator/something_went_wrong.html')

password_generator/templates/base.html
{% load static %}
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'img/fav.ico'%}">
        <meta name="theme-color" content="#ffffff">
        <link rel="stylesheet" href="{% static '/css/bootstrap.min.css'%}">
        <title>{% block title %} Password generation {% endblock %} </title>
    </head>
    <body>
        <header class="text-center border-bottom">
            {% include 'includes/header.html'%}
        </header>
        <main>
            {% block content %}
              <div style="margin-top: 1%; margin-bottom: 1%">

                <p class="text-center"> 
                    OMG!!! Looks like I forgot to implement<span style='color:blue'> content block</span> in this template, sorry for that:(
                </p>
                    <img src="{% static 'img/sorry.png' %}" class="img-fluid rounded mx-auto d-block" alt="image desc">
            </div>
            {% endblock %}
        </main>
        <footer class="border-top text-center py-3 fixed-bottom">
            {% include 'includes/footer.html' %}
        </footer>
    </body>

</html>

password_generator/templates/generator/gen.html
{% extends 'base.html' %}

{% block title %}
    MMM, We're gonna do some Goofy PASSWORDS
{% endblock title %}
    


{% block content %}
    <div class='d-flex justify-content-center'>
        <h3>
            Select which options suit you best
        </h3>
    </div>
    <form class="form-check-verttical d-flex flex-column align-items-center" action="{% url 'generator:pwd' %}">
          <div>
            <label for="" class="form-label">Select length</label>
            <select name="length" id="">
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12" selected>12</option>
                <option value="13">13</option>
                <option value="14">14</option>
            </select>
          </div>
          <div>
            <label class="form-check-label" for="">
                With Uppercase letters
            </label>
            <input class="form-check-input" name="uppercase" type="checkbox" style='margin-left:5px' value="True" checked>
          </div>
          <div>
            <label class="form-check-label">
                Numbers in password
            </label>
            <input class="form-check-input" name='numbers' type="checkbox" style='margin-left:5px' value="True" checked>
          </div>
          <div>
            <label class="form-check-label">
                Special chars in password
            </label>
            <input class="form-check-input" name='special' type="checkbox" style='margin-left:5px' value="True">
          </div>
          <button type="submit" style='margin-top:5px'class="btn btn-primary">Generate password</button>
    </form>
    <div class='d-flex flex-column align-items-center'>
      <a type="submit" style='margin-top:5%' class="btn btn-outline-danger" href='{% url "generator:sorry" %}'> Give it a try</a>
    </div>
{% endblock content %}

password_generator/templates/generator/password.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Your password {% endblock %}

{% block content %}
  <br>
  <h1 class='text-center'><span class='badge bg-dark'>Your password</span></h1>
  <br>
  <h3 class='text-center'>{{ pwd }}</h3>
  <br>
  <img src="{% static 'img/blow_your_mind.gif' %}" class="img-fluid rounded mx-auto d-block" alt="image desc">

{% endblock content %}

password_generator/templates/generator/something_went_wrong.html
{% extends 'base.html'%}

password_generator/templates/includes/footer.html
<p>© 2022 Copyright <span style="color:red">Key</span>Gen</p>    

password_generator/templates/includes/header.html
<h1> 
    <a href='{% url "generator:gen" %}' style='color:black' class="text-decoration-none">Serious <span style='color:red'>Key</span>Generator!!! </a>
</h1> 